version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Test
          command: |
            sudo pip install -r requirements.txt
            python tests.py