version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Test
          command: |
            sudo pip install -r requirements.txt
            python tests.py
      - store_test_results:
          path: build/test-results
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t codechan .
      - run: docker tag codechan $DOCKER_USER/codechan:$CIRCLE_SHA1 
      - run: docker tag codechan $DOCKER_USER/codechan:latest

      # deploy the image
      - run: docker push $DOCKER_USER/codechan:$CIRCLE_SHA1 
      - run: docker push $DOCKER_USER/codechan:latest
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: |
            scp docker-compose.yaml ubuntu@35.195.63.194:.
            ssh ubuntu@35.195.63.194 "docker-compose pull || true && docker-compose up -d"
            #ssh ubuntu@34.77.102.142 "docker container stop codechan_con || true && docker container prune -f && docker container run --name codechan_con -d -p 5000:5000 arcrl/codechan"
workflows:
  version: 2
  myworkflow:
    jobs:
      - test
      #- dockerize:
     #     requires:
     #       - test
      - deploy:
          requires:
            - test